const qs=[
{id:'g1',tag:'節足動物',q:'図のAはどの部分ですか？',img:'svg/grasshopper-textbook.svg',choices:['頭','胸','腹','前ばね'],a:'頭',ex:'Aは頭です。触角や目がある部分です。'},
{id:'g2',tag:'節足動物',q:'図のBはどの部分ですか？',img:'svg/grasshopper-textbook.svg',choices:['頭','胸','腹','気門'],a:'胸',ex:'Bは胸です。昆虫のあしは胸に3対つきます。'},
{id:'g3',tag:'節足動物',q:'図のCはどの部分ですか？',img:'svg/grasshopper-textbook.svg',choices:['頭','胸','腹','触角'],a:'腹',ex:'Cは腹です。腹の側面には気門があります。'},
{id:'g4',tag:'節足動物',q:'バッタのあしがついている部分は？',img:'svg/grasshopper-textbook.svg',choices:['頭','胸','腹','はね'],a:'胸',ex:'昆虫の6本のあしはすべて胸についています。'},
{id:'g5',tag:'節足動物',q:'空気の出入り口である小さな穴は？',img:'svg/grasshopper-textbook.svg',choices:['気門','えら','外とう膜','入水管'],a:'気門',ex:'昆虫は気門から空気を取り込みます。'},
{id:'m1',tag:'軟体動物',q:'イカの内臓を包む膜は？',img:'svg/squid-clam-textbook.svg',choices:['外とう膜','細胞膜','鼓膜','横隔膜'],a:'外とう膜',ex:'軟体動物では外とう膜が内臓を包みます。'},
{id:'m2',tag:'軟体動物',q:'アサリで水が入る管は？',img:'svg/squid-clam-textbook.svg',choices:['入水管','出水管','気門','輸卵管'],a:'入水管',ex:'水は入水管から入り、えらを通ります。'},
{id:'m3',tag:'軟体動物',q:'アサリで水が出る管は？',img:'svg/squid-clam-textbook.svg',choices:['入水管','出水管','気門','外とう膜'],a:'出水管',ex:'えらを通った水は出水管から出ます。'},
{id:'m4',tag:'軟体動物',q:'イカとアサリに共通する呼吸器官は？',img:'svg/squid-clam-textbook.svg',choices:['えら','肺','気管','皮ふだけ'],a:'えら',ex:'イカとアサリはどちらもえらで呼吸します。'},
{id:'m5',tag:'軟体動物',q:'イカとアサリは何動物ですか？',img:'svg/squid-clam-textbook.svg',choices:['軟体動物','節足動物','脊椎動物','刺胞動物'],a:'軟体動物',ex:'体がやわらかく、外とう膜をもつ軟体動物です。'}];
const $=id=>document.getElementById(id);let state={list:[],i:0,correct:0,mode:'study',answered:false};const key='rika-diagram-v3';
function store(){return JSON.parse(localStorage.getItem(key)||'{"answered":0,"correct":0,"wrong":[]}')}function save(x){localStorage.setItem(key,JSON.stringify(x))}function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function updateHome(){const p=store();$('homeRate').textContent=(p.answered?Math.round(p.correct/p.answered*100):0)+'%';$('wrongCount').textContent=p.wrong.length}
function start(mode){state.mode=mode;const p=store();state.list=mode==='review'?qs.filter(x=>p.wrong.includes(x.id)):mode==='test'?shuffle(qs).slice(0,10):shuffle(qs);if(!state.list.length){alert('復習する問題はまだありません。');return}state.i=0;state.correct=0;show('quiz');render()}
function render(){const x=state.list[state.i];state.answered=false;$('num').textContent=state.i+1;$('total').textContent=state.list.length;$('barFill').style.width=((state.i)/state.list.length*100)+'%';$('tag').textContent=x.tag;$('questionText').textContent=x.q;$('figure').innerHTML=`<img src="${x.img}" alt="${x.tag}の図">`;$('choices').innerHTML='';shuffle(x.choices).forEach(c=>{const b=document.createElement('button');b.className='choice';b.textContent=c;b.onclick=()=>answer(c,b);$('choices').appendChild(b)});$('feedback').hidden=true;$('nextBtn').hidden=true}
function answer(c,b){if(state.answered)return;state.answered=true;const x=state.list[state.i],ok=c===x.a;if(ok)state.correct++;document.querySelectorAll('.choice').forEach(n=>{n.disabled=true;if(n.textContent===x.a)n.classList.add('correct')});if(!ok)b.classList.add('wrong');$('feedback').hidden=false;$('feedback').innerHTML=`<b>${ok?'正解！':'おしい！'}</b><br>${x.ex}`;$('nextBtn').hidden=false;const p=store();p.answered++;if(ok)p.correct++;const w=new Set(p.wrong);ok?w.delete(x.id):w.add(x.id);p.wrong=[...w];save(p);updateHome()}
function next(){if(state.i<state.list.length-1){state.i++;render()}else{const n=Math.round(state.correct/state.list.length*100);$('score').textContent=n+'点';$('resultText').textContent=n>=90?'図と名称がしっかり結びついています。':n>=70?'よくできました。間違いだけ復習するとさらに安定します。':'図を見ながら名称をもう一度確認しよう。';show('result')}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('nextBtn').onclick=next;$('backBtn').onclick=()=>show('home');$('homeBtn').onclick=()=>show('home');$('againBtn').onclick=()=>start(state.mode);$('resetBtn').onclick=()=>{if(confirm('学習記録をリセットしますか？')){localStorage.removeItem(key);updateHome()}};updateHome();