const $=id=>document.getElementById(id),KEY='rikaPrivateImagesV1',PROG='rikaPrivateProgressV1';
const questions=[
{id:'b1',img:'page8',chapter:'単元8',topic:'バッタ',q:'①の部分は何ですか？',crop:[45,175,650,400],mark:[105,120,'①'],choices:['頭','胸','腹','はね'],a:'頭',hint:'触角や目がある部分です。',ex:'バッタの体は頭・胸・腹の3つに分かれます。'},
{id:'b2',img:'page8',chapter:'単元8',topic:'バッタ',q:'②の部分は何ですか？',crop:[45,175,650,400],mark:[225,125,'②'],choices:['頭','胸','腹','触角'],a:'胸',hint:'6本のあしがついています。',ex:'昆虫のあしは胸に3対ついています。'},
{id:'b3',img:'page8',chapter:'単元8',topic:'バッタ',q:'③の部分は何ですか？',crop:[45,175,650,400],mark:[405,127,'③'],choices:['頭','胸','腹','外骨格'],a:'腹',hint:'体の後ろ側の長い部分です。',ex:'バッタの後ろ側の部分が腹です。'},
{id:'i1',img:'page8',chapter:'単元8',topic:'軟体動物',q:'①で示した膜を何といいますか？',crop:[40,500,690,500],mark:[225,100,'①'],choices:['外とう膜','細胞膜','鼓膜','横隔膜'],a:'外とう膜',hint:'イカとアサリに共通します。',ex:'外とう膜は内臓を包む膜です。'},
{id:'a1',img:'page8',chapter:'単元8',topic:'アサリ',q:'②の管は何ですか？',crop:[350,500,560,490],mark:[365,150,'②'],choices:['入水管','出水管','気門','水管'],a:'出水管',hint:'水を体外へ出す管です。',ex:'上側が出水管、下側が入水管です。'},
{id:'v1',img:'page7',chapter:'単元7',topic:'脊椎動物',q:'Aのグループに入る組み合わせは？',crop:[610,70,800,410],mark:[105,70,'A'],choices:['魚類と両生類','は虫類と鳥類','鳥類と哺乳類','魚類と哺乳類'],a:'魚類と両生類',hint:'卵を水中に産むグループです。',ex:'Aには魚類と両生類が入ります。'},
{id:'v2',img:'page7',chapter:'単元7',topic:'脊椎動物',q:'Bのグループに共通する特徴は？',crop:[610,70,800,410],mark:[390,70,'B'],choices:['水中に卵を産む','殻のある卵を陸上に産む','胎生である','一生えら呼吸'],a:'殻のある卵を陸上に産む',hint:'は虫類と鳥類に共通します。',ex:'は虫類と鳥類は殻のある卵を陸上に産みます。'},
{id:'v3',img:'page7',chapter:'単元7',topic:'脊椎動物',q:'哺乳類の子の生まれ方は？',crop:[35,520,650,390],mark:[480,90,'①'],choices:['卵生','胎生','分裂','出芽'],a:'胎生',hint:'母親の体内で育ちます。',ex:'哺乳類は基本的に胎生です。'}];
let mode='all',list=[],idx=0,correct=0,locked=false;
function data(){return JSON.parse(localStorage.getItem(KEY)||'{}')}function prog(){return JSON.parse(localStorage.getItem(PROG)||'{"answered":0,"correct":0,"wrong":[]}')}function saveProg(p){localStorage.setItem(PROG,JSON.stringify(p))}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id))}
function refresh(){const d=data();['page7','page8'].forEach(k=>{const box=$(k+'Thumb');box.innerHTML=d[k]?`<img src="${d[k]}">`:'画像未登録'});const p=prog();$('wrongCount').textContent=p.wrong.length+'問';$('status').textContent=d.page7&&d.page8?'画像登録済み':'最初に画像を2枚登録してください'}
function register(input,key){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const d=data();d[key]=r.result;try{localStorage.setItem(KEY,JSON.stringify(d));refresh()}catch(e){alert('画像の容量が大きすぎます。写真を少し小さくして再登録してください。')}};r.readAsDataURL(f)}
function start(m){const d=data();if(!d.page7||!d.page8){alert('先に単元7・8の画像を登録してください。');return}mode=m;const p=prog();list=m==='review'?questions.filter(q=>p.wrong.includes(q.id)):[...questions].sort(()=>Math.random()-.5);if(!list.length){alert('復習する問題はまだありません。');return}idx=0;correct=0;show('quiz');render()}
function render(){locked=false;const q=list[idx];$('counter').textContent=`${idx+1}/${list.length}`;$('barFill').style.width=`${idx/list.length*100}%`;$('chapter').textContent=q.chapter;$('topic').textContent=q.topic;$('questionText').textContent=q.q;$('feedback').className='feedback hidden';$('nextBtn').classList.add('hidden');$('choices').innerHTML='';[...q.choices].sort(()=>Math.random()-.5).forEach(c=>{const b=document.createElement('button');b.className='choice';b.textContent=c;b.onclick=()=>answer(c,b);$('choices').appendChild(b)});draw(q)}
function draw(q){const img=new Image();img.onload=()=>{const [x,y,w,h]=q.crop,c=$('canvas'),ctx=c.getContext('2d'),scale=Math.min(1100/w,1.6);c.width=w*scale;c.height=h*scale;ctx.drawImage(img,x,y,w,h,0,0,c.width,c.height);const [mx,my,label]=q.mark;ctx.beginPath();ctx.arc(mx*scale,my*scale,27*scale,0,Math.PI*2);ctx.fillStyle='rgba(255,255,255,.94)';ctx.fill();ctx.lineWidth=4*scale;ctx.strokeStyle='#d33';ctx.stroke();ctx.fillStyle='#b21f1f';ctx.font=`bold ${25*scale}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,mx*scale,my*scale)};img.src=data()[q.img]}
function answer(choice,button){if(locked)return;locked=true;const q=list[idx],ok=choice===q.a;if(ok)correct++;document.querySelectorAll('.choice').forEach(b=>{b.disabled=true;if(b.textContent===q.a)b.classList.add('correct')});if(!ok)button.classList.add('wrong');$('feedback').className='feedback '+(ok?'ok':'ng');$('feedback').innerHTML=`<b>${ok?'正解！':'おしい！'}</b><br>${q.ex}`;$('nextBtn').classList.remove('hidden');const p=prog();p.answered++;if(ok)p.correct++;const w=new Set(p.wrong);ok?w.delete(q.id):w.add(q.id);p.wrong=[...w];saveProg(p)}
function finish(){show('result');const s=Math.round(correct/list.length*100);$('score').textContent=s+'点';$('resultText').textContent=s>=90?'図を正確に読み取れています！':s>=70?'よくできました。間違いを復習しよう。':'番号と名称をセットで覚えよう。'}
$('page7Input').onchange=e=>register(e.target,'page7');$('page8Input').onchange=e=>register(e.target,'page8');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('hintBtn').onclick=()=>alert(list[idx].hint);$('nextBtn').onclick=()=>idx<list.length-1?(idx++,render()):finish();$('homeBtn').onclick=()=>{refresh();show('home')};$('againBtn').onclick=()=>start(mode);$('clearImages').onclick=()=>{if(confirm('登録画像を削除しますか？')){localStorage.removeItem(KEY);refresh()}};refresh();